// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orchestrator.proto

// ─────────────────────────────────────────────────────────────────────────────
//  A2WS — Adaptive Asynchronous Work-Stealing
//  Sistema de procesamiento de imágenes distribuido
//
//  Topología fija:
//    • 1 Servidor Java (Quarkus)  →  Orquestador  (puerto 50051)
//    • 3 Nodos Python             →  WorkerNode   (puerto 50052 c/u)
//    • Cada nodo: 6 workers, cola local = 6 slots
// ─────────────────────────────────────────────────────────────────────────────

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	proto "orchestrator-node/proto"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrchestratorName is the fully-qualified name of the Orchestrator service.
	OrchestratorName = "worker.Orchestrator"
	// WorkerNodeName is the fully-qualified name of the WorkerNode service.
	WorkerNodeName = "worker.WorkerNode"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrchestratorRegisterNodeProcedure is the fully-qualified name of the Orchestrator's RegisterNode
	// RPC.
	OrchestratorRegisterNodeProcedure = "/worker.Orchestrator/RegisterNode"
	// OrchestratorLogEventProcedure is the fully-qualified name of the Orchestrator's LogEvent RPC.
	OrchestratorLogEventProcedure = "/worker.Orchestrator/LogEvent"
	// OrchestratorPullTasksProcedure is the fully-qualified name of the Orchestrator's PullTasks RPC.
	OrchestratorPullTasksProcedure = "/worker.Orchestrator/PullTasks"
	// OrchestratorSubmitResultProcedure is the fully-qualified name of the Orchestrator's SubmitResult
	// RPC.
	OrchestratorSubmitResultProcedure = "/worker.Orchestrator/SubmitResult"
	// OrchestratorStealTasksProcedure is the fully-qualified name of the Orchestrator's StealTasks RPC.
	OrchestratorStealTasksProcedure = "/worker.Orchestrator/StealTasks"
	// OrchestratorUpdateTaskProgressProcedure is the fully-qualified name of the Orchestrator's
	// UpdateTaskProgress RPC.
	OrchestratorUpdateTaskProgressProcedure = "/worker.Orchestrator/UpdateTaskProgress"
	// OrchestratorSendHeartbeatProcedure is the fully-qualified name of the Orchestrator's
	// SendHeartbeat RPC.
	OrchestratorSendHeartbeatProcedure = "/worker.Orchestrator/SendHeartbeat"
	// OrchestratorGetQueueStatusProcedure is the fully-qualified name of the Orchestrator's
	// GetQueueStatus RPC.
	OrchestratorGetQueueStatusProcedure = "/worker.Orchestrator/GetQueueStatus"
	// OrchestratorWatchQueueProcedure is the fully-qualified name of the Orchestrator's WatchQueue RPC.
	OrchestratorWatchQueueProcedure = "/worker.Orchestrator/WatchQueue"
	// WorkerNodeGetMetricsProcedure is the fully-qualified name of the WorkerNode's GetMetrics RPC.
	WorkerNodeGetMetricsProcedure = "/worker.WorkerNode/GetMetrics"
	// WorkerNodeYieldTasksProcedure is the fully-qualified name of the WorkerNode's YieldTasks RPC.
	WorkerNodeYieldTasksProcedure = "/worker.WorkerNode/YieldTasks"
)

// OrchestratorClient is a client for the worker.Orchestrator service.
type OrchestratorClient interface {
	// Autodescubrimiento: el nodo se registra al arrancar.
	// Si ya existía → UPDATED; si es nuevo → REGISTERED.
	// Usar también como heartbeat de registro con métricas iniciales.
	RegisterNode(context.Context, *connect.Request[proto.RegisterNodeRequest]) (*connect.Response[proto.RegisterNodeResponse], error)
	// Centralización de logs de los nodos
	LogEvent(context.Context, *connect.Request[proto.LogRequest]) (*connect.Response[proto.LogResponse], error)
	// A2WS PULL: el nodo pide trabajo cuando tiene slots libres
	PullTasks(context.Context, *connect.Request[proto.PullRequest]) (*connect.Response[proto.PullResponse], error)
	// El nodo entrega el resultado de una imagen procesada
	SubmitResult(context.Context, *connect.Request[proto.TaskResult]) (*connect.Response[proto.Ack], error)
	// El nodo solicita robar tareas de otro nodo (orquestador arbitra)
	StealTasks(context.Context, *connect.Request[proto.StealRequest]) (*connect.Response[proto.StealResponse], error)
	// El nodo reporta progreso de una tarea en curso (UI en tiempo real)
	UpdateTaskProgress(context.Context, *connect.Request[proto.TaskProgress]) (*connect.Response[proto.Ack], error)
	// Heartbeat ligero: "sigo vivo" + métricas en tiempo real.
	// Si falla 3 veces consecutivas → el servidor re-encola sus tareas.
	SendHeartbeat(context.Context, *connect.Request[proto.HeartbeatRequest]) (*connect.Response[proto.Ack], error)
	// Estado completo de colas (para dashboard / decisiones A2WS)
	GetQueueStatus(context.Context, *connect.Request[proto.QueueStatusRequest]) (*connect.Response[proto.QueueStatusResponse], error)
	// Stream: el orquestador empuja actualizaciones a quien esté suscrito
	WatchQueue(context.Context, *connect.Request[proto.QueueStatusRequest]) (*connect.ServerStreamForClient[proto.QueueStatusResponse], error)
}

// NewOrchestratorClient constructs a client for the worker.Orchestrator service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrchestratorClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrchestratorClient {
	baseURL = strings.TrimRight(baseURL, "/")
	orchestratorMethods := proto.File_orchestrator_proto.Services().ByName("Orchestrator").Methods()
	return &orchestratorClient{
		registerNode: connect.NewClient[proto.RegisterNodeRequest, proto.RegisterNodeResponse](
			httpClient,
			baseURL+OrchestratorRegisterNodeProcedure,
			connect.WithSchema(orchestratorMethods.ByName("RegisterNode")),
			connect.WithClientOptions(opts...),
		),
		logEvent: connect.NewClient[proto.LogRequest, proto.LogResponse](
			httpClient,
			baseURL+OrchestratorLogEventProcedure,
			connect.WithSchema(orchestratorMethods.ByName("LogEvent")),
			connect.WithClientOptions(opts...),
		),
		pullTasks: connect.NewClient[proto.PullRequest, proto.PullResponse](
			httpClient,
			baseURL+OrchestratorPullTasksProcedure,
			connect.WithSchema(orchestratorMethods.ByName("PullTasks")),
			connect.WithClientOptions(opts...),
		),
		submitResult: connect.NewClient[proto.TaskResult, proto.Ack](
			httpClient,
			baseURL+OrchestratorSubmitResultProcedure,
			connect.WithSchema(orchestratorMethods.ByName("SubmitResult")),
			connect.WithClientOptions(opts...),
		),
		stealTasks: connect.NewClient[proto.StealRequest, proto.StealResponse](
			httpClient,
			baseURL+OrchestratorStealTasksProcedure,
			connect.WithSchema(orchestratorMethods.ByName("StealTasks")),
			connect.WithClientOptions(opts...),
		),
		updateTaskProgress: connect.NewClient[proto.TaskProgress, proto.Ack](
			httpClient,
			baseURL+OrchestratorUpdateTaskProgressProcedure,
			connect.WithSchema(orchestratorMethods.ByName("UpdateTaskProgress")),
			connect.WithClientOptions(opts...),
		),
		sendHeartbeat: connect.NewClient[proto.HeartbeatRequest, proto.Ack](
			httpClient,
			baseURL+OrchestratorSendHeartbeatProcedure,
			connect.WithSchema(orchestratorMethods.ByName("SendHeartbeat")),
			connect.WithClientOptions(opts...),
		),
		getQueueStatus: connect.NewClient[proto.QueueStatusRequest, proto.QueueStatusResponse](
			httpClient,
			baseURL+OrchestratorGetQueueStatusProcedure,
			connect.WithSchema(orchestratorMethods.ByName("GetQueueStatus")),
			connect.WithClientOptions(opts...),
		),
		watchQueue: connect.NewClient[proto.QueueStatusRequest, proto.QueueStatusResponse](
			httpClient,
			baseURL+OrchestratorWatchQueueProcedure,
			connect.WithSchema(orchestratorMethods.ByName("WatchQueue")),
			connect.WithClientOptions(opts...),
		),
	}
}

// orchestratorClient implements OrchestratorClient.
type orchestratorClient struct {
	registerNode       *connect.Client[proto.RegisterNodeRequest, proto.RegisterNodeResponse]
	logEvent           *connect.Client[proto.LogRequest, proto.LogResponse]
	pullTasks          *connect.Client[proto.PullRequest, proto.PullResponse]
	submitResult       *connect.Client[proto.TaskResult, proto.Ack]
	stealTasks         *connect.Client[proto.StealRequest, proto.StealResponse]
	updateTaskProgress *connect.Client[proto.TaskProgress, proto.Ack]
	sendHeartbeat      *connect.Client[proto.HeartbeatRequest, proto.Ack]
	getQueueStatus     *connect.Client[proto.QueueStatusRequest, proto.QueueStatusResponse]
	watchQueue         *connect.Client[proto.QueueStatusRequest, proto.QueueStatusResponse]
}

// RegisterNode calls worker.Orchestrator.RegisterNode.
func (c *orchestratorClient) RegisterNode(ctx context.Context, req *connect.Request[proto.RegisterNodeRequest]) (*connect.Response[proto.RegisterNodeResponse], error) {
	return c.registerNode.CallUnary(ctx, req)
}

// LogEvent calls worker.Orchestrator.LogEvent.
func (c *orchestratorClient) LogEvent(ctx context.Context, req *connect.Request[proto.LogRequest]) (*connect.Response[proto.LogResponse], error) {
	return c.logEvent.CallUnary(ctx, req)
}

// PullTasks calls worker.Orchestrator.PullTasks.
func (c *orchestratorClient) PullTasks(ctx context.Context, req *connect.Request[proto.PullRequest]) (*connect.Response[proto.PullResponse], error) {
	return c.pullTasks.CallUnary(ctx, req)
}

// SubmitResult calls worker.Orchestrator.SubmitResult.
func (c *orchestratorClient) SubmitResult(ctx context.Context, req *connect.Request[proto.TaskResult]) (*connect.Response[proto.Ack], error) {
	return c.submitResult.CallUnary(ctx, req)
}

// StealTasks calls worker.Orchestrator.StealTasks.
func (c *orchestratorClient) StealTasks(ctx context.Context, req *connect.Request[proto.StealRequest]) (*connect.Response[proto.StealResponse], error) {
	return c.stealTasks.CallUnary(ctx, req)
}

// UpdateTaskProgress calls worker.Orchestrator.UpdateTaskProgress.
func (c *orchestratorClient) UpdateTaskProgress(ctx context.Context, req *connect.Request[proto.TaskProgress]) (*connect.Response[proto.Ack], error) {
	return c.updateTaskProgress.CallUnary(ctx, req)
}

// SendHeartbeat calls worker.Orchestrator.SendHeartbeat.
func (c *orchestratorClient) SendHeartbeat(ctx context.Context, req *connect.Request[proto.HeartbeatRequest]) (*connect.Response[proto.Ack], error) {
	return c.sendHeartbeat.CallUnary(ctx, req)
}

// GetQueueStatus calls worker.Orchestrator.GetQueueStatus.
func (c *orchestratorClient) GetQueueStatus(ctx context.Context, req *connect.Request[proto.QueueStatusRequest]) (*connect.Response[proto.QueueStatusResponse], error) {
	return c.getQueueStatus.CallUnary(ctx, req)
}

// WatchQueue calls worker.Orchestrator.WatchQueue.
func (c *orchestratorClient) WatchQueue(ctx context.Context, req *connect.Request[proto.QueueStatusRequest]) (*connect.ServerStreamForClient[proto.QueueStatusResponse], error) {
	return c.watchQueue.CallServerStream(ctx, req)
}

// OrchestratorHandler is an implementation of the worker.Orchestrator service.
type OrchestratorHandler interface {
	// Autodescubrimiento: el nodo se registra al arrancar.
	// Si ya existía → UPDATED; si es nuevo → REGISTERED.
	// Usar también como heartbeat de registro con métricas iniciales.
	RegisterNode(context.Context, *connect.Request[proto.RegisterNodeRequest]) (*connect.Response[proto.RegisterNodeResponse], error)
	// Centralización de logs de los nodos
	LogEvent(context.Context, *connect.Request[proto.LogRequest]) (*connect.Response[proto.LogResponse], error)
	// A2WS PULL: el nodo pide trabajo cuando tiene slots libres
	PullTasks(context.Context, *connect.Request[proto.PullRequest]) (*connect.Response[proto.PullResponse], error)
	// El nodo entrega el resultado de una imagen procesada
	SubmitResult(context.Context, *connect.Request[proto.TaskResult]) (*connect.Response[proto.Ack], error)
	// El nodo solicita robar tareas de otro nodo (orquestador arbitra)
	StealTasks(context.Context, *connect.Request[proto.StealRequest]) (*connect.Response[proto.StealResponse], error)
	// El nodo reporta progreso de una tarea en curso (UI en tiempo real)
	UpdateTaskProgress(context.Context, *connect.Request[proto.TaskProgress]) (*connect.Response[proto.Ack], error)
	// Heartbeat ligero: "sigo vivo" + métricas en tiempo real.
	// Si falla 3 veces consecutivas → el servidor re-encola sus tareas.
	SendHeartbeat(context.Context, *connect.Request[proto.HeartbeatRequest]) (*connect.Response[proto.Ack], error)
	// Estado completo de colas (para dashboard / decisiones A2WS)
	GetQueueStatus(context.Context, *connect.Request[proto.QueueStatusRequest]) (*connect.Response[proto.QueueStatusResponse], error)
	// Stream: el orquestador empuja actualizaciones a quien esté suscrito
	WatchQueue(context.Context, *connect.Request[proto.QueueStatusRequest], *connect.ServerStream[proto.QueueStatusResponse]) error
}

// NewOrchestratorHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrchestratorHandler(svc OrchestratorHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	orchestratorMethods := proto.File_orchestrator_proto.Services().ByName("Orchestrator").Methods()
	orchestratorRegisterNodeHandler := connect.NewUnaryHandler(
		OrchestratorRegisterNodeProcedure,
		svc.RegisterNode,
		connect.WithSchema(orchestratorMethods.ByName("RegisterNode")),
		connect.WithHandlerOptions(opts...),
	)
	orchestratorLogEventHandler := connect.NewUnaryHandler(
		OrchestratorLogEventProcedure,
		svc.LogEvent,
		connect.WithSchema(orchestratorMethods.ByName("LogEvent")),
		connect.WithHandlerOptions(opts...),
	)
	orchestratorPullTasksHandler := connect.NewUnaryHandler(
		OrchestratorPullTasksProcedure,
		svc.PullTasks,
		connect.WithSchema(orchestratorMethods.ByName("PullTasks")),
		connect.WithHandlerOptions(opts...),
	)
	orchestratorSubmitResultHandler := connect.NewUnaryHandler(
		OrchestratorSubmitResultProcedure,
		svc.SubmitResult,
		connect.WithSchema(orchestratorMethods.ByName("SubmitResult")),
		connect.WithHandlerOptions(opts...),
	)
	orchestratorStealTasksHandler := connect.NewUnaryHandler(
		OrchestratorStealTasksProcedure,
		svc.StealTasks,
		connect.WithSchema(orchestratorMethods.ByName("StealTasks")),
		connect.WithHandlerOptions(opts...),
	)
	orchestratorUpdateTaskProgressHandler := connect.NewUnaryHandler(
		OrchestratorUpdateTaskProgressProcedure,
		svc.UpdateTaskProgress,
		connect.WithSchema(orchestratorMethods.ByName("UpdateTaskProgress")),
		connect.WithHandlerOptions(opts...),
	)
	orchestratorSendHeartbeatHandler := connect.NewUnaryHandler(
		OrchestratorSendHeartbeatProcedure,
		svc.SendHeartbeat,
		connect.WithSchema(orchestratorMethods.ByName("SendHeartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	orchestratorGetQueueStatusHandler := connect.NewUnaryHandler(
		OrchestratorGetQueueStatusProcedure,
		svc.GetQueueStatus,
		connect.WithSchema(orchestratorMethods.ByName("GetQueueStatus")),
		connect.WithHandlerOptions(opts...),
	)
	orchestratorWatchQueueHandler := connect.NewServerStreamHandler(
		OrchestratorWatchQueueProcedure,
		svc.WatchQueue,
		connect.WithSchema(orchestratorMethods.ByName("WatchQueue")),
		connect.WithHandlerOptions(opts...),
	)
	return "/worker.Orchestrator/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrchestratorRegisterNodeProcedure:
			orchestratorRegisterNodeHandler.ServeHTTP(w, r)
		case OrchestratorLogEventProcedure:
			orchestratorLogEventHandler.ServeHTTP(w, r)
		case OrchestratorPullTasksProcedure:
			orchestratorPullTasksHandler.ServeHTTP(w, r)
		case OrchestratorSubmitResultProcedure:
			orchestratorSubmitResultHandler.ServeHTTP(w, r)
		case OrchestratorStealTasksProcedure:
			orchestratorStealTasksHandler.ServeHTTP(w, r)
		case OrchestratorUpdateTaskProgressProcedure:
			orchestratorUpdateTaskProgressHandler.ServeHTTP(w, r)
		case OrchestratorSendHeartbeatProcedure:
			orchestratorSendHeartbeatHandler.ServeHTTP(w, r)
		case OrchestratorGetQueueStatusProcedure:
			orchestratorGetQueueStatusHandler.ServeHTTP(w, r)
		case OrchestratorWatchQueueProcedure:
			orchestratorWatchQueueHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrchestratorHandler returns CodeUnimplemented from all methods.
type UnimplementedOrchestratorHandler struct{}

func (UnimplementedOrchestratorHandler) RegisterNode(context.Context, *connect.Request[proto.RegisterNodeRequest]) (*connect.Response[proto.RegisterNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("worker.Orchestrator.RegisterNode is not implemented"))
}

func (UnimplementedOrchestratorHandler) LogEvent(context.Context, *connect.Request[proto.LogRequest]) (*connect.Response[proto.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("worker.Orchestrator.LogEvent is not implemented"))
}

func (UnimplementedOrchestratorHandler) PullTasks(context.Context, *connect.Request[proto.PullRequest]) (*connect.Response[proto.PullResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("worker.Orchestrator.PullTasks is not implemented"))
}

func (UnimplementedOrchestratorHandler) SubmitResult(context.Context, *connect.Request[proto.TaskResult]) (*connect.Response[proto.Ack], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("worker.Orchestrator.SubmitResult is not implemented"))
}

func (UnimplementedOrchestratorHandler) StealTasks(context.Context, *connect.Request[proto.StealRequest]) (*connect.Response[proto.StealResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("worker.Orchestrator.StealTasks is not implemented"))
}

func (UnimplementedOrchestratorHandler) UpdateTaskProgress(context.Context, *connect.Request[proto.TaskProgress]) (*connect.Response[proto.Ack], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("worker.Orchestrator.UpdateTaskProgress is not implemented"))
}

func (UnimplementedOrchestratorHandler) SendHeartbeat(context.Context, *connect.Request[proto.HeartbeatRequest]) (*connect.Response[proto.Ack], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("worker.Orchestrator.SendHeartbeat is not implemented"))
}

func (UnimplementedOrchestratorHandler) GetQueueStatus(context.Context, *connect.Request[proto.QueueStatusRequest]) (*connect.Response[proto.QueueStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("worker.Orchestrator.GetQueueStatus is not implemented"))
}

func (UnimplementedOrchestratorHandler) WatchQueue(context.Context, *connect.Request[proto.QueueStatusRequest], *connect.ServerStream[proto.QueueStatusResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("worker.Orchestrator.WatchQueue is not implemented"))
}

// WorkerNodeClient is a client for the worker.WorkerNode service.
type WorkerNodeClient interface {
	// El orquestador consulta métricas detalladas de este nodo
	GetMetrics(context.Context, *connect.Request[proto.QueueStatusRequest]) (*connect.Response[proto.NodeMetrics], error)
	// El orquestador le pide que ceda tareas (work-stealing coordinado)
	YieldTasks(context.Context, *connect.Request[proto.StealRequest]) (*connect.Response[proto.StealResponse], error)
}

// NewWorkerNodeClient constructs a client for the worker.WorkerNode service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkerNodeClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkerNodeClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workerNodeMethods := proto.File_orchestrator_proto.Services().ByName("WorkerNode").Methods()
	return &workerNodeClient{
		getMetrics: connect.NewClient[proto.QueueStatusRequest, proto.NodeMetrics](
			httpClient,
			baseURL+WorkerNodeGetMetricsProcedure,
			connect.WithSchema(workerNodeMethods.ByName("GetMetrics")),
			connect.WithClientOptions(opts...),
		),
		yieldTasks: connect.NewClient[proto.StealRequest, proto.StealResponse](
			httpClient,
			baseURL+WorkerNodeYieldTasksProcedure,
			connect.WithSchema(workerNodeMethods.ByName("YieldTasks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workerNodeClient implements WorkerNodeClient.
type workerNodeClient struct {
	getMetrics *connect.Client[proto.QueueStatusRequest, proto.NodeMetrics]
	yieldTasks *connect.Client[proto.StealRequest, proto.StealResponse]
}

// GetMetrics calls worker.WorkerNode.GetMetrics.
func (c *workerNodeClient) GetMetrics(ctx context.Context, req *connect.Request[proto.QueueStatusRequest]) (*connect.Response[proto.NodeMetrics], error) {
	return c.getMetrics.CallUnary(ctx, req)
}

// YieldTasks calls worker.WorkerNode.YieldTasks.
func (c *workerNodeClient) YieldTasks(ctx context.Context, req *connect.Request[proto.StealRequest]) (*connect.Response[proto.StealResponse], error) {
	return c.yieldTasks.CallUnary(ctx, req)
}

// WorkerNodeHandler is an implementation of the worker.WorkerNode service.
type WorkerNodeHandler interface {
	// El orquestador consulta métricas detalladas de este nodo
	GetMetrics(context.Context, *connect.Request[proto.QueueStatusRequest]) (*connect.Response[proto.NodeMetrics], error)
	// El orquestador le pide que ceda tareas (work-stealing coordinado)
	YieldTasks(context.Context, *connect.Request[proto.StealRequest]) (*connect.Response[proto.StealResponse], error)
}

// NewWorkerNodeHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkerNodeHandler(svc WorkerNodeHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workerNodeMethods := proto.File_orchestrator_proto.Services().ByName("WorkerNode").Methods()
	workerNodeGetMetricsHandler := connect.NewUnaryHandler(
		WorkerNodeGetMetricsProcedure,
		svc.GetMetrics,
		connect.WithSchema(workerNodeMethods.ByName("GetMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	workerNodeYieldTasksHandler := connect.NewUnaryHandler(
		WorkerNodeYieldTasksProcedure,
		svc.YieldTasks,
		connect.WithSchema(workerNodeMethods.ByName("YieldTasks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/worker.WorkerNode/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkerNodeGetMetricsProcedure:
			workerNodeGetMetricsHandler.ServeHTTP(w, r)
		case WorkerNodeYieldTasksProcedure:
			workerNodeYieldTasksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkerNodeHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkerNodeHandler struct{}

func (UnimplementedWorkerNodeHandler) GetMetrics(context.Context, *connect.Request[proto.QueueStatusRequest]) (*connect.Response[proto.NodeMetrics], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("worker.WorkerNode.GetMetrics is not implemented"))
}

func (UnimplementedWorkerNodeHandler) YieldTasks(context.Context, *connect.Request[proto.StealRequest]) (*connect.Response[proto.StealResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("worker.WorkerNode.YieldTasks is not implemented"))
}
