# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import imagenode_pb2 as proto_dot_imagenode__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/imagenode_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessToPath = channel.unary_unary(
                '/imagenode.ImageNodeService/ProcessToPath',
                request_serializer=proto_dot_imagenode__pb2.ProcessRequest.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.PathResponse.FromString,
                _registered_method=True)
        self.ProcessToData = channel.unary_unary(
                '/imagenode.ImageNodeService/ProcessToData',
                request_serializer=proto_dot_imagenode__pb2.ProcessRequest.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.DataResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/imagenode.ImageNodeService/HealthCheck',
                request_serializer=proto_dot_imagenode__pb2.EmptyRequest.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/imagenode.ImageNodeService/GetMetrics',
                request_serializer=proto_dot_imagenode__pb2.EmptyRequest.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.UploadLargeImage = channel.stream_unary(
                '/imagenode.ImageNodeService/UploadLargeImage',
                request_serializer=proto_dot_imagenode__pb2.ImageChunk.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.DataResponse.FromString,
                _registered_method=True)
        self.StreamBatchProcess = channel.stream_stream(
                '/imagenode.ImageNodeService/StreamBatchProcess',
                request_serializer=proto_dot_imagenode__pb2.ProcessRequest.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.DataResponse.FromString,
                _registered_method=True)
        self.GetProcessedFilePaths = channel.unary_unary(
                '/imagenode.ImageNodeService/GetProcessedFilePaths',
                request_serializer=proto_dot_imagenode__pb2.EmptyRequest.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.PathListResponse.FromString,
                _registered_method=True)
        self.FindPathByName = channel.unary_unary(
                '/imagenode.ImageNodeService/FindPathByName',
                request_serializer=proto_dot_imagenode__pb2.FileNameRequest.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.PathResponse.FromString,
                _registered_method=True)
        self.GetProcessedImages = channel.unary_unary(
                '/imagenode.ImageNodeService/GetProcessedImages',
                request_serializer=proto_dot_imagenode__pb2.EmptyRequest.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.DataListResponse.FromString,
                _registered_method=True)
        self.FindImageByName = channel.unary_unary(
                '/imagenode.ImageNodeService/FindImageByName',
                request_serializer=proto_dot_imagenode__pb2.FileNameRequest.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.DataResponse.FromString,
                _registered_method=True)
        self.ProcessBatch = channel.unary_unary(
                '/imagenode.ImageNodeService/ProcessBatch',
                request_serializer=proto_dot_imagenode__pb2.BatchRequest.SerializeToString,
                response_deserializer=proto_dot_imagenode__pb2.BatchDataResponse.FromString,
                _registered_method=True)


class ImageNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessToPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessToData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadLargeImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBatchProcess(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessedFilePaths(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPathByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessedImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindImageByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessToPath': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessToPath,
                    request_deserializer=proto_dot_imagenode__pb2.ProcessRequest.FromString,
                    response_serializer=proto_dot_imagenode__pb2.PathResponse.SerializeToString,
            ),
            'ProcessToData': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessToData,
                    request_deserializer=proto_dot_imagenode__pb2.ProcessRequest.FromString,
                    response_serializer=proto_dot_imagenode__pb2.DataResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_imagenode__pb2.EmptyRequest.FromString,
                    response_serializer=proto_dot_imagenode__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=proto_dot_imagenode__pb2.EmptyRequest.FromString,
                    response_serializer=proto_dot_imagenode__pb2.MetricsResponse.SerializeToString,
            ),
            'UploadLargeImage': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadLargeImage,
                    request_deserializer=proto_dot_imagenode__pb2.ImageChunk.FromString,
                    response_serializer=proto_dot_imagenode__pb2.DataResponse.SerializeToString,
            ),
            'StreamBatchProcess': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamBatchProcess,
                    request_deserializer=proto_dot_imagenode__pb2.ProcessRequest.FromString,
                    response_serializer=proto_dot_imagenode__pb2.DataResponse.SerializeToString,
            ),
            'GetProcessedFilePaths': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessedFilePaths,
                    request_deserializer=proto_dot_imagenode__pb2.EmptyRequest.FromString,
                    response_serializer=proto_dot_imagenode__pb2.PathListResponse.SerializeToString,
            ),
            'FindPathByName': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPathByName,
                    request_deserializer=proto_dot_imagenode__pb2.FileNameRequest.FromString,
                    response_serializer=proto_dot_imagenode__pb2.PathResponse.SerializeToString,
            ),
            'GetProcessedImages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessedImages,
                    request_deserializer=proto_dot_imagenode__pb2.EmptyRequest.FromString,
                    response_serializer=proto_dot_imagenode__pb2.DataListResponse.SerializeToString,
            ),
            'FindImageByName': grpc.unary_unary_rpc_method_handler(
                    servicer.FindImageByName,
                    request_deserializer=proto_dot_imagenode__pb2.FileNameRequest.FromString,
                    response_serializer=proto_dot_imagenode__pb2.DataResponse.SerializeToString,
            ),
            'ProcessBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessBatch,
                    request_deserializer=proto_dot_imagenode__pb2.BatchRequest.FromString,
                    response_serializer=proto_dot_imagenode__pb2.BatchDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imagenode.ImageNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imagenode.ImageNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessToPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagenode.ImageNodeService/ProcessToPath',
            proto_dot_imagenode__pb2.ProcessRequest.SerializeToString,
            proto_dot_imagenode__pb2.PathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessToData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagenode.ImageNodeService/ProcessToData',
            proto_dot_imagenode__pb2.ProcessRequest.SerializeToString,
            proto_dot_imagenode__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagenode.ImageNodeService/HealthCheck',
            proto_dot_imagenode__pb2.EmptyRequest.SerializeToString,
            proto_dot_imagenode__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagenode.ImageNodeService/GetMetrics',
            proto_dot_imagenode__pb2.EmptyRequest.SerializeToString,
            proto_dot_imagenode__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadLargeImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/imagenode.ImageNodeService/UploadLargeImage',
            proto_dot_imagenode__pb2.ImageChunk.SerializeToString,
            proto_dot_imagenode__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBatchProcess(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/imagenode.ImageNodeService/StreamBatchProcess',
            proto_dot_imagenode__pb2.ProcessRequest.SerializeToString,
            proto_dot_imagenode__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessedFilePaths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagenode.ImageNodeService/GetProcessedFilePaths',
            proto_dot_imagenode__pb2.EmptyRequest.SerializeToString,
            proto_dot_imagenode__pb2.PathListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPathByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagenode.ImageNodeService/FindPathByName',
            proto_dot_imagenode__pb2.FileNameRequest.SerializeToString,
            proto_dot_imagenode__pb2.PathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessedImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagenode.ImageNodeService/GetProcessedImages',
            proto_dot_imagenode__pb2.EmptyRequest.SerializeToString,
            proto_dot_imagenode__pb2.DataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindImageByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagenode.ImageNodeService/FindImageByName',
            proto_dot_imagenode__pb2.FileNameRequest.SerializeToString,
            proto_dot_imagenode__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagenode.ImageNodeService/ProcessBatch',
            proto_dot_imagenode__pb2.BatchRequest.SerializeToString,
            proto_dot_imagenode__pb2.BatchDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
