# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import orchestrator_pb2 as proto_dot_orchestrator__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorStub(object):
    """═══════════════════════════════════════════════════════════════════════════
    SERVICIOS
    ═══════════════════════════════════════════════════════════════════════════

    ── Expuesto por el Servidor Java (Orquestador) ───────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullTasks = channel.unary_unary(
                '/worker.Orchestrator/PullTasks',
                request_serializer=proto_dot_orchestrator__pb2.PullRequest.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.PullResponse.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/worker.Orchestrator/SubmitResult',
                request_serializer=proto_dot_orchestrator__pb2.TaskResult.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.Ack.FromString,
                _registered_method=True)
        self.StealTasks = channel.unary_unary(
                '/worker.Orchestrator/StealTasks',
                request_serializer=proto_dot_orchestrator__pb2.StealRequest.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.StealResponse.FromString,
                _registered_method=True)
        self.UpdateTaskProgress = channel.unary_unary(
                '/worker.Orchestrator/UpdateTaskProgress',
                request_serializer=proto_dot_orchestrator__pb2.TaskProgress.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.Ack.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/worker.Orchestrator/SendHeartbeat',
                request_serializer=proto_dot_orchestrator__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.Ack.FromString,
                _registered_method=True)
        self.GetQueueStatus = channel.unary_unary(
                '/worker.Orchestrator/GetQueueStatus',
                request_serializer=proto_dot_orchestrator__pb2.QueueStatusRequest.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.QueueStatusResponse.FromString,
                _registered_method=True)
        self.WatchQueue = channel.unary_stream(
                '/worker.Orchestrator/WatchQueue',
                request_serializer=proto_dot_orchestrator__pb2.QueueStatusRequest.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.QueueStatusResponse.FromString,
                _registered_method=True)


class OrchestratorServicer(object):
    """═══════════════════════════════════════════════════════════════════════════
    SERVICIOS
    ═══════════════════════════════════════════════════════════════════════════

    ── Expuesto por el Servidor Java (Orquestador) ───────────────────────────────
    """

    def PullTasks(self, request, context):
        """A2WS PULL: el nodo pide trabajo cuando tiene slots libres
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """El nodo entrega el resultado de una imagen procesada
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StealTasks(self, request, context):
        """El nodo solicita robar tareas de otro nodo (orquestador arbitra)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTaskProgress(self, request, context):
        """El nodo reporta progreso de una tarea en curso (UI en tiempo real)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Heartbeat: "sigo vivo"; si falla 3 veces → re-encolar sus tareas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueStatus(self, request, context):
        """Estado completo de colas (para dashboard / decisiones A2WS)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchQueue(self, request, context):
        """Stream: el orquestador empuja actualizaciones a quien esté suscrito
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.PullTasks,
                    request_deserializer=proto_dot_orchestrator__pb2.PullRequest.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.PullResponse.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=proto_dot_orchestrator__pb2.TaskResult.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.Ack.SerializeToString,
            ),
            'StealTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.StealTasks,
                    request_deserializer=proto_dot_orchestrator__pb2.StealRequest.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.StealResponse.SerializeToString,
            ),
            'UpdateTaskProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTaskProgress,
                    request_deserializer=proto_dot_orchestrator__pb2.TaskProgress.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.Ack.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=proto_dot_orchestrator__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.Ack.SerializeToString,
            ),
            'GetQueueStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueStatus,
                    request_deserializer=proto_dot_orchestrator__pb2.QueueStatusRequest.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.QueueStatusResponse.SerializeToString,
            ),
            'WatchQueue': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchQueue,
                    request_deserializer=proto_dot_orchestrator__pb2.QueueStatusRequest.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.QueueStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.Orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker.Orchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Orchestrator(object):
    """═══════════════════════════════════════════════════════════════════════════
    SERVICIOS
    ═══════════════════════════════════════════════════════════════════════════

    ── Expuesto por el Servidor Java (Orquestador) ───────────────────────────────
    """

    @staticmethod
    def PullTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.Orchestrator/PullTasks',
            proto_dot_orchestrator__pb2.PullRequest.SerializeToString,
            proto_dot_orchestrator__pb2.PullResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.Orchestrator/SubmitResult',
            proto_dot_orchestrator__pb2.TaskResult.SerializeToString,
            proto_dot_orchestrator__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StealTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.Orchestrator/StealTasks',
            proto_dot_orchestrator__pb2.StealRequest.SerializeToString,
            proto_dot_orchestrator__pb2.StealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTaskProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.Orchestrator/UpdateTaskProgress',
            proto_dot_orchestrator__pb2.TaskProgress.SerializeToString,
            proto_dot_orchestrator__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.Orchestrator/SendHeartbeat',
            proto_dot_orchestrator__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_orchestrator__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.Orchestrator/GetQueueStatus',
            proto_dot_orchestrator__pb2.QueueStatusRequest.SerializeToString,
            proto_dot_orchestrator__pb2.QueueStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/worker.Orchestrator/WatchQueue',
            proto_dot_orchestrator__pb2.QueueStatusRequest.SerializeToString,
            proto_dot_orchestrator__pb2.QueueStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerNodeStub(object):
    """── Expuesto por cada Nodo Python ─────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetrics = channel.unary_unary(
                '/worker.WorkerNode/GetMetrics',
                request_serializer=proto_dot_orchestrator__pb2.QueueStatusRequest.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.NodeMetrics.FromString,
                _registered_method=True)
        self.YieldTasks = channel.unary_unary(
                '/worker.WorkerNode/YieldTasks',
                request_serializer=proto_dot_orchestrator__pb2.StealRequest.SerializeToString,
                response_deserializer=proto_dot_orchestrator__pb2.StealResponse.FromString,
                _registered_method=True)


class WorkerNodeServicer(object):
    """── Expuesto por cada Nodo Python ─────────────────────────────────────────────
    """

    def GetMetrics(self, request, context):
        """El orquestador consulta métricas detalladas de este nodo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def YieldTasks(self, request, context):
        """El orquestador le pide que ceda tareas (work-stealing coordinado)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=proto_dot_orchestrator__pb2.QueueStatusRequest.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.NodeMetrics.SerializeToString,
            ),
            'YieldTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.YieldTasks,
                    request_deserializer=proto_dot_orchestrator__pb2.StealRequest.FromString,
                    response_serializer=proto_dot_orchestrator__pb2.StealResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.WorkerNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker.WorkerNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerNode(object):
    """── Expuesto por cada Nodo Python ─────────────────────────────────────────────
    """

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerNode/GetMetrics',
            proto_dot_orchestrator__pb2.QueueStatusRequest.SerializeToString,
            proto_dot_orchestrator__pb2.NodeMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def YieldTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerNode/YieldTasks',
            proto_dot_orchestrator__pb2.StealRequest.SerializeToString,
            proto_dot_orchestrator__pb2.StealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
