# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import worker_node_pb2 as proto_dot_worker__node__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/worker_node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/worker.WorkerControlService/SubmitTask',
                request_serializer=proto_dot_worker__node__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=proto_dot_worker__node__pb2.SubmitTaskReply.FromString,
                _registered_method=True)
        self.GetNodeStatus = channel.unary_unary(
                '/worker.WorkerControlService/GetNodeStatus',
                request_serializer=proto_dot_worker__node__pb2.GetNodeStatusRequest.SerializeToString,
                response_deserializer=proto_dot_worker__node__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/worker.WorkerControlService/CancelTask',
                request_serializer=proto_dot_worker__node__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=proto_dot_worker__node__pb2.CancelTaskReply.FromString,
                _registered_method=True)
        self.DrainNode = channel.unary_unary(
                '/worker.WorkerControlService/DrainNode',
                request_serializer=proto_dot_worker__node__pb2.DrainNodeRequest.SerializeToString,
                response_deserializer=proto_dot_worker__node__pb2.DrainNodeReply.FromString,
                _registered_method=True)
        self.ShutdownNode = channel.unary_unary(
                '/worker.WorkerControlService/ShutdownNode',
                request_serializer=proto_dot_worker__node__pb2.ShutdownNodeRequest.SerializeToString,
                response_deserializer=proto_dot_worker__node__pb2.ShutdownNodeReply.FromString,
                _registered_method=True)


class WorkerControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutdownNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=proto_dot_worker__node__pb2.SubmitTaskRequest.FromString,
                    response_serializer=proto_dot_worker__node__pb2.SubmitTaskReply.SerializeToString,
            ),
            'GetNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeStatus,
                    request_deserializer=proto_dot_worker__node__pb2.GetNodeStatusRequest.FromString,
                    response_serializer=proto_dot_worker__node__pb2.NodeStatus.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=proto_dot_worker__node__pb2.CancelTaskRequest.FromString,
                    response_serializer=proto_dot_worker__node__pb2.CancelTaskReply.SerializeToString,
            ),
            'DrainNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainNode,
                    request_deserializer=proto_dot_worker__node__pb2.DrainNodeRequest.FromString,
                    response_serializer=proto_dot_worker__node__pb2.DrainNodeReply.SerializeToString,
            ),
            'ShutdownNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutdownNode,
                    request_deserializer=proto_dot_worker__node__pb2.ShutdownNodeRequest.FromString,
                    response_serializer=proto_dot_worker__node__pb2.ShutdownNodeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.WorkerControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker.WorkerControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerControlService/SubmitTask',
            proto_dot_worker__node__pb2.SubmitTaskRequest.SerializeToString,
            proto_dot_worker__node__pb2.SubmitTaskReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerControlService/GetNodeStatus',
            proto_dot_worker__node__pb2.GetNodeStatusRequest.SerializeToString,
            proto_dot_worker__node__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerControlService/CancelTask',
            proto_dot_worker__node__pb2.CancelTaskRequest.SerializeToString,
            proto_dot_worker__node__pb2.CancelTaskReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerControlService/DrainNode',
            proto_dot_worker__node__pb2.DrainNodeRequest.SerializeToString,
            proto_dot_worker__node__pb2.DrainNodeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShutdownNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerControlService/ShutdownNode',
            proto_dot_worker__node__pb2.ShutdownNodeRequest.SerializeToString,
            proto_dot_worker__node__pb2.ShutdownNodeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorCallbackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportProgress = channel.unary_unary(
                '/worker.CoordinatorCallbackService/ReportProgress',
                request_serializer=proto_dot_worker__node__pb2.ProgressEvent.SerializeToString,
                response_deserializer=proto_dot_worker__node__pb2.ReportAck.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/worker.CoordinatorCallbackService/ReportResult',
                request_serializer=proto_dot_worker__node__pb2.ExecutionResult.SerializeToString,
                response_deserializer=proto_dot_worker__node__pb2.ReportAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/worker.CoordinatorCallbackService/Heartbeat',
                request_serializer=proto_dot_worker__node__pb2.CoordinatorHeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_worker__node__pb2.CoordinatorHeartbeatReply.FromString,
                _registered_method=True)


class CoordinatorCallbackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorCallbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProgress,
                    request_deserializer=proto_dot_worker__node__pb2.ProgressEvent.FromString,
                    response_serializer=proto_dot_worker__node__pb2.ReportAck.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=proto_dot_worker__node__pb2.ExecutionResult.FromString,
                    response_serializer=proto_dot_worker__node__pb2.ReportAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_worker__node__pb2.CoordinatorHeartbeatRequest.FromString,
                    response_serializer=proto_dot_worker__node__pb2.CoordinatorHeartbeatReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.CoordinatorCallbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker.CoordinatorCallbackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorCallbackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.CoordinatorCallbackService/ReportProgress',
            proto_dot_worker__node__pb2.ProgressEvent.SerializeToString,
            proto_dot_worker__node__pb2.ReportAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.CoordinatorCallbackService/ReportResult',
            proto_dot_worker__node__pb2.ExecutionResult.SerializeToString,
            proto_dot_worker__node__pb2.ReportAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.CoordinatorCallbackService/Heartbeat',
            proto_dot_worker__node__pb2.CoordinatorHeartbeatRequest.SerializeToString,
            proto_dot_worker__node__pb2.CoordinatorHeartbeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
