// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orchestrator.proto

// ─────────────────────────────────────────────────────────────────────────────
//  A2WS — Adaptive Asynchronous Work-Stealing
//  Sistema de procesamiento de imágenes distribuido
//
//  Topología fija:
//    • 1 Servidor Java (Quarkus)  →  Orquestador  (puerto 50051)
//    • 3 Nodos Python             →  WorkerNode   (puerto 50052 c/u)
//    • Cada nodo: 6 workers, cola local = 6 slots
// ─────────────────────────────────────────────────────────────────────────────

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransformationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformationItem) Reset() {
	*x = TransformationItem{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformationItem) ProtoMessage() {}

func (x *TransformationItem) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformationItem.ProtoReflect.Descriptor instead.
func (*TransformationItem) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *TransformationItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransformationItem) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type TransformationPipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TransformationItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformationPipeline) Reset() {
	*x = TransformationPipeline{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformationPipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformationPipeline) ProtoMessage() {}

func (x *TransformationPipeline) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformationPipeline.ProtoReflect.Descriptor instead.
func (*TransformationPipeline) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *TransformationPipeline) GetItems() []*TransformationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Tarea de imagen publicada por el orquestador
type ImageTask struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	TaskId                 string                  `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ImageData              []byte                  `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // <-- ¡AQUÍ VIAJAN LOS BITS! (Adiós Base64)
	Filename               string                  `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`                    // Ej: "reloj.png"
	TransformationPipeline *TransformationPipeline `protobuf:"bytes,4,opt,name=transformation_pipeline,json=transformationPipeline,proto3" json:"transformation_pipeline,omitempty"`
	EnqueueTs              int64                   `protobuf:"varint,5,opt,name=enqueue_ts,json=enqueueTs,proto3" json:"enqueue_ts,omitempty"`                                                        // Tiempo en el que entró a la cola
	Priority               int32                   `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`                                                                           // Prioridad (0 por defecto)
	TargetWidth            int32                   `protobuf:"varint,7,opt,name=target_width,json=targetWidth,proto3" json:"target_width,omitempty"`                                                  // (Opcional) Ancho a redimensionar
	TargetHeight           int32                   `protobuf:"varint,8,opt,name=target_height,json=targetHeight,proto3" json:"target_height,omitempty"`                                               // (Opcional) Alto a redimensionar
	ImageFormat            string                  `protobuf:"bytes,9,opt,name=image_format,json=imageFormat,proto3" json:"image_format,omitempty"`                                                   // (Opcional) Formato de la imagen
	Metadata               map[string]string       `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadatos de contexto opcionales
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ImageTask) Reset() {
	*x = ImageTask{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageTask) ProtoMessage() {}

func (x *ImageTask) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageTask.ProtoReflect.Descriptor instead.
func (*ImageTask) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *ImageTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ImageTask) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ImageTask) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImageTask) GetTransformationPipeline() *TransformationPipeline {
	if x != nil {
		return x.TransformationPipeline
	}
	return nil
}

func (x *ImageTask) GetEnqueueTs() int64 {
	if x != nil {
		return x.EnqueueTs
	}
	return 0
}

func (x *ImageTask) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ImageTask) GetTargetWidth() int32 {
	if x != nil {
		return x.TargetWidth
	}
	return 0
}

func (x *ImageTask) GetTargetHeight() int32 {
	if x != nil {
		return x.TargetHeight
	}
	return 0
}

func (x *ImageTask) GetImageFormat() string {
	if x != nil {
		return x.ImageFormat
	}
	return ""
}

func (x *ImageTask) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Métricas en tiempo real de un nodo
type NodeMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IpAddress       string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	RamUsedMb       float32                `protobuf:"fixed32,3,opt,name=ram_used_mb,json=ramUsedMb,proto3" json:"ram_used_mb,omitempty"`
	RamTotalMb      float32                `protobuf:"fixed32,4,opt,name=ram_total_mb,json=ramTotalMb,proto3" json:"ram_total_mb,omitempty"`
	CpuPercent      float32                `protobuf:"fixed32,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	WorkersBusy     int32                  `protobuf:"varint,6,opt,name=workers_busy,json=workersBusy,proto3" json:"workers_busy,omitempty"`
	WorkersTotal    int32                  `protobuf:"varint,7,opt,name=workers_total,json=workersTotal,proto3" json:"workers_total,omitempty"`           // siempre 6 en esta topología
	QueueSize       int32                  `protobuf:"varint,8,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`                    // tareas en cola local ahora mismo
	QueueCapacity   int32                  `protobuf:"varint,9,opt,name=queue_capacity,json=queueCapacity,proto3" json:"queue_capacity,omitempty"`        // siempre 6 en esta topología
	TasksDone       int32                  `protobuf:"varint,10,opt,name=tasks_done,json=tasksDone,proto3" json:"tasks_done,omitempty"`                   // acumulado desde el arranque
	StealsPerformed int32                  `protobuf:"varint,11,opt,name=steals_performed,json=stealsPerformed,proto3" json:"steals_performed,omitempty"` // work-steals realizados
	AvgLatencyMs    float32                `protobuf:"fixed32,12,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`       // media de las últimas 100 tareas
	P95LatencyMs    float32                `protobuf:"fixed32,13,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`       // percentil 95 de latencia
	UptimeSeconds   int64                  `protobuf:"varint,14,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Status          string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"` // "IDLE" | "BUSY" | "STEALING" | "ERROR"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *NodeMetrics) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeMetrics) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NodeMetrics) GetRamUsedMb() float32 {
	if x != nil {
		return x.RamUsedMb
	}
	return 0
}

func (x *NodeMetrics) GetRamTotalMb() float32 {
	if x != nil {
		return x.RamTotalMb
	}
	return 0
}

func (x *NodeMetrics) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeMetrics) GetWorkersBusy() int32 {
	if x != nil {
		return x.WorkersBusy
	}
	return 0
}

func (x *NodeMetrics) GetWorkersTotal() int32 {
	if x != nil {
		return x.WorkersTotal
	}
	return 0
}

func (x *NodeMetrics) GetQueueSize() int32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *NodeMetrics) GetQueueCapacity() int32 {
	if x != nil {
		return x.QueueCapacity
	}
	return 0
}

func (x *NodeMetrics) GetTasksDone() int32 {
	if x != nil {
		return x.TasksDone
	}
	return 0
}

func (x *NodeMetrics) GetStealsPerformed() int32 {
	if x != nil {
		return x.StealsPerformed
	}
	return 0
}

func (x *NodeMetrics) GetAvgLatencyMs() float32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *NodeMetrics) GetP95LatencyMs() float32 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *NodeMetrics) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *NodeMetrics) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ─── Pull (nodo de Python pide trabajo al orquestador Java) ────────
type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`           // "node-1" | "node-2" | "node-3"
	SlotsFree     int32                  `protobuf:"varint,2,opt,name=slots_free,json=slotsFree,proto3" json:"slots_free,omitempty"` // cuántos slots libres tiene (workers inactivos)
	Metrics       *NodeMetrics           `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`                       // estado actual del nodo adjunto al pull
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *PullRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PullRequest) GetSlotsFree() int32 {
	if x != nil {
		return x.SlotsFree
	}
	return 0
}

func (x *PullRequest) GetMetrics() *NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type PullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*ImageTask           `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`                        // Envía 1 o más tareas con sus bytes adentro
	QueueDry      bool                   `protobuf:"varint,2,opt,name=queue_dry,json=queueDry,proto3" json:"queue_dry,omitempty"` // true = no hay más trabajo por ahora
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *PullResponse) GetTasks() []*ImageTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *PullResponse) GetQueueDry() bool {
	if x != nil {
		return x.QueueDry
	}
	return false
}

// ─── Submit (nodo de Python entrega resultado al orquestador Java) ─
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // "node-1-w3"
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ResultData    []byte                 `protobuf:"bytes,5,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`                                                      // <-- ¡AQUÍ VUELVEN LOS BITS PROCESADOS!
	ErrorMsg      string                 `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`                                                            // vacío si success=true
	StartTs       int64                  `protobuf:"varint,7,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`                                                              // epoch-ms inicio procesamiento
	FinishTs      int64                  `protobuf:"varint,8,opt,name=finish_ts,json=finishTs,proto3" json:"finish_ts,omitempty"`                                                           // epoch-ms fin
	ProcessingMs  int32                  `protobuf:"varint,9,opt,name=processing_ms,json=processingMs,proto3" json:"processing_ms,omitempty"`                                               // Cuántos milisegundos le tomó a Python
	Metrics       *NodeMetrics           `protobuf:"bytes,10,opt,name=metrics,proto3" json:"metrics,omitempty"`                                                                             // snapshot justo después de terminar
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadatos enriquecidos (OCR, Inferencia, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TaskResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *TaskResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *TaskResult) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *TaskResult) GetFinishTs() int64 {
	if x != nil {
		return x.FinishTs
	}
	return 0
}

func (x *TaskResult) GetProcessingMs() int32 {
	if x != nil {
		return x.ProcessingMs
	}
	return 0
}

func (x *TaskResult) GetMetrics() *NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TaskResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ─── Work-Stealing ────────────────────────────────────────────────────────────
type StealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThiefNodeId   string                 `protobuf:"bytes,1,opt,name=thief_node_id,json=thiefNodeId,proto3" json:"thief_node_id,omitempty"`    // quién quiere robar
	VictimNodeId  string                 `protobuf:"bytes,2,opt,name=victim_node_id,json=victimNodeId,proto3" json:"victim_node_id,omitempty"` // a quién le roba (más cargado)
	StealCount    int32                  `protobuf:"varint,3,opt,name=steal_count,json=stealCount,proto3" json:"steal_count,omitempty"`        // cuántas tareas solicita
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StealRequest) Reset() {
	*x = StealRequest{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StealRequest) ProtoMessage() {}

func (x *StealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StealRequest.ProtoReflect.Descriptor instead.
func (*StealRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *StealRequest) GetThiefNodeId() string {
	if x != nil {
		return x.ThiefNodeId
	}
	return ""
}

func (x *StealRequest) GetVictimNodeId() string {
	if x != nil {
		return x.VictimNodeId
	}
	return ""
}

func (x *StealRequest) GetStealCount() int32 {
	if x != nil {
		return x.StealCount
	}
	return 0
}

type StealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StolenTasks   []*ImageTask           `protobuf:"bytes,1,rep,name=stolen_tasks,json=stolenTasks,proto3" json:"stolen_tasks,omitempty"`
	Allowed       bool                   `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // motivo si !allowed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StealResponse) Reset() {
	*x = StealResponse{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StealResponse) ProtoMessage() {}

func (x *StealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StealResponse.ProtoReflect.Descriptor instead.
func (*StealResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *StealResponse) GetStolenTasks() []*ImageTask {
	if x != nil {
		return x.StolenTasks
	}
	return nil
}

func (x *StealResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *StealResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ─── Progreso de tarea (opcional, para progreso en UI) ───────────────────────
type TaskProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId           string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ProgressPercentage int32                  `protobuf:"varint,3,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"` // 0–100
	StatusMessage      string                 `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`                 // "Aplicando filtro Sobel..."
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *TaskProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgress) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskProgress) GetProgressPercentage() int32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *TaskProgress) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

// ─── Monitoreo de colas ───────────────────────────────────────────────────────
type QueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // node_id o "dashboard"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusRequest) Reset() {
	*x = QueueStatusRequest{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusRequest) ProtoMessage() {}

func (x *QueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusRequest.ProtoReflect.Descriptor instead.
func (*QueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *QueueStatusRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type NodeQueueInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	QueueSize     int32                  `protobuf:"varint,2,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
	QueueCap      int32                  `protobuf:"varint,3,opt,name=queue_cap,json=queueCap,proto3" json:"queue_cap,omitempty"`
	WorkersBusy   int32                  `protobuf:"varint,4,opt,name=workers_busy,json=workersBusy,proto3" json:"workers_busy,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeQueueInfo) Reset() {
	*x = NodeQueueInfo{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeQueueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeQueueInfo) ProtoMessage() {}

func (x *NodeQueueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeQueueInfo.ProtoReflect.Descriptor instead.
func (*NodeQueueInfo) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *NodeQueueInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeQueueInfo) GetQueueSize() int32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *NodeQueueInfo) GetQueueCap() int32 {
	if x != nil {
		return x.QueueCap
	}
	return 0
}

func (x *NodeQueueInfo) GetWorkersBusy() int32 {
	if x != nil {
		return x.WorkersBusy
	}
	return 0
}

func (x *NodeQueueInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *NodeQueueInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueueStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CentralQueueSize int32                  `protobuf:"varint,1,opt,name=central_queue_size,json=centralQueueSize,proto3" json:"central_queue_size,omitempty"`
	CentralQueueCap  int32                  `protobuf:"varint,2,opt,name=central_queue_cap,json=centralQueueCap,proto3" json:"central_queue_cap,omitempty"`
	Nodes            []*NodeQueueInfo       `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // epoch-ms de la snapshot
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueueStatusResponse) Reset() {
	*x = QueueStatusResponse{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusResponse) ProtoMessage() {}

func (x *QueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusResponse.ProtoReflect.Descriptor instead.
func (*QueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *QueueStatusResponse) GetCentralQueueSize() int32 {
	if x != nil {
		return x.CentralQueueSize
	}
	return 0
}

func (x *QueueStatusResponse) GetCentralQueueCap() int32 {
	if x != nil {
		return x.CentralQueueCap
	}
	return 0
}

func (x *QueueStatusResponse) GetNodes() []*NodeQueueInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *QueueStatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ─── Registro de nodo (autodescubrimiento) ───────────────────────────────────
type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`          // Identificador único del nodo (ej. "nodo-go-1")
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // IP real del nodo en la red
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                           // Puerto gRPC en el que el nodo expone su servicio
	Metrics       *NodeMetrics           `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`                      // Snapshot inicial de métricas (workers, cola, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterNodeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterNodeRequest) GetMetrics() *NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type RegisterNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// "REGISTERED" = nodo nuevo registrado correctamente
	// "UPDATED"    = nodo ya existía, solo se actualizó su estado
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"` // Mensaje descriptivo opcional del servidor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterNodeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterNodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterNodeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ─── Heartbeat ────────────────────────────────────────────────────────────────
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Metrics       *NodeMetrics           `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"` // métricas ligeras junto al ping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *HeartbeatRequest) GetMetrics() *NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// ─── Ack genérico ─────────────────────────────────────────────────────────────
type LogRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ImageUuid        string                 `protobuf:"bytes,2,opt,name=image_uuid,json=imageUuid,proto3" json:"image_uuid,omitempty"`
	Level            string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"` // INFO, WARNING, ERROR, CRITICAL
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	TransformationId int32                  `protobuf:"varint,5,opt,name=transformation_id,json=transformationId,proto3" json:"transformation_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *LogRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LogRequest) GetImageUuid() string {
	if x != nil {
		return x.ImageUuid
	}
	return ""
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetTransformationId() int32 {
	if x != nil {
		return x.TransformationId
	}
	return 0
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *LogResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x12\x06worker\"I\n" +
	"\x12TransformationItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\tR\n" +
	"paramsJson\"J\n" +
	"\x16TransformationPipeline\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.worker.TransformationItemR\x05items\"\xd8\x03\n" +
	"\tImageTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12W\n" +
	"\x17transformation_pipeline\x18\x04 \x01(\v2\x1e.worker.TransformationPipelineR\x16transformationPipeline\x12\x1d\n" +
	"\n" +
	"enqueue_ts\x18\x05 \x01(\x03R\tenqueueTs\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12!\n" +
	"\ftarget_width\x18\a \x01(\x05R\vtargetWidth\x12#\n" +
	"\rtarget_height\x18\b \x01(\x05R\ftargetHeight\x12!\n" +
	"\fimage_format\x18\t \x01(\tR\vimageFormat\x12;\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\x1f.worker.ImageTask.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x04\n" +
	"\vNodeMetrics\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1e\n" +
	"\vram_used_mb\x18\x03 \x01(\x02R\tramUsedMb\x12 \n" +
	"\fram_total_mb\x18\x04 \x01(\x02R\n" +
	"ramTotalMb\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x02R\n" +
	"cpuPercent\x12!\n" +
	"\fworkers_busy\x18\x06 \x01(\x05R\vworkersBusy\x12#\n" +
	"\rworkers_total\x18\a \x01(\x05R\fworkersTotal\x12\x1d\n" +
	"\n" +
	"queue_size\x18\b \x01(\x05R\tqueueSize\x12%\n" +
	"\x0equeue_capacity\x18\t \x01(\x05R\rqueueCapacity\x12\x1d\n" +
	"\n" +
	"tasks_done\x18\n" +
	" \x01(\x05R\ttasksDone\x12)\n" +
	"\x10steals_performed\x18\v \x01(\x05R\x0fstealsPerformed\x12$\n" +
	"\x0eavg_latency_ms\x18\f \x01(\x02R\favgLatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\r \x01(\x02R\fp95LatencyMs\x12%\n" +
	"\x0euptime_seconds\x18\x0e \x01(\x03R\ruptimeSeconds\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\"t\n" +
	"\vPullRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"slots_free\x18\x02 \x01(\x05R\tslotsFree\x12-\n" +
	"\ametrics\x18\x03 \x01(\v2\x13.worker.NodeMetricsR\ametrics\"T\n" +
	"\fPullResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.worker.ImageTaskR\x05tasks\x12\x1b\n" +
	"\tqueue_dry\x18\x02 \x01(\bR\bqueueDry\"\xba\x03\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_data\x18\x05 \x01(\fR\n" +
	"resultData\x12\x1b\n" +
	"\terror_msg\x18\x06 \x01(\tR\berrorMsg\x12\x19\n" +
	"\bstart_ts\x18\a \x01(\x03R\astartTs\x12\x1b\n" +
	"\tfinish_ts\x18\b \x01(\x03R\bfinishTs\x12#\n" +
	"\rprocessing_ms\x18\t \x01(\x05R\fprocessingMs\x12-\n" +
	"\ametrics\x18\n" +
	" \x01(\v2\x13.worker.NodeMetricsR\ametrics\x12<\n" +
	"\bmetadata\x18\v \x03(\v2 .worker.TaskResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\fStealRequest\x12\"\n" +
	"\rthief_node_id\x18\x01 \x01(\tR\vthiefNodeId\x12$\n" +
	"\x0evictim_node_id\x18\x02 \x01(\tR\fvictimNodeId\x12\x1f\n" +
	"\vsteal_count\x18\x03 \x01(\x05R\n" +
	"stealCount\"w\n" +
	"\rStealResponse\x124\n" +
	"\fstolen_tasks\x18\x01 \x03(\v2\x11.worker.ImageTaskR\vstolenTasks\x12\x18\n" +
	"\aallowed\x18\x02 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x9c\x01\n" +
	"\fTaskProgress\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12/\n" +
	"\x13progress_percentage\x18\x03 \x01(\x05R\x12progressPercentage\x12%\n" +
	"\x0estatus_message\x18\x04 \x01(\tR\rstatusMessage\"7\n" +
	"\x12QueueStatusRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\"\xbd\x01\n" +
	"\rNodeQueueInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"queue_size\x18\x02 \x01(\x05R\tqueueSize\x12\x1b\n" +
	"\tqueue_cap\x18\x03 \x01(\x05R\bqueueCap\x12!\n" +
	"\fworkers_busy\x18\x04 \x01(\x05R\vworkersBusy\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xba\x01\n" +
	"\x13QueueStatusResponse\x12,\n" +
	"\x12central_queue_size\x18\x01 \x01(\x05R\x10centralQueueSize\x12*\n" +
	"\x11central_queue_cap\x18\x02 \x01(\x05R\x0fcentralQueueCap\x12+\n" +
	"\x05nodes\x18\x03 \x03(\v2\x15.worker.NodeQueueInfoR\x05nodes\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x90\x01\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12-\n" +
	"\ametrics\x18\x04 \x01(\v2\x13.worker.NodeMetricsR\ametrics\"P\n" +
	"\x14RegisterNodeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"y\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12-\n" +
	"\ametrics\x18\x03 \x01(\v2\x13.worker.NodeMetricsR\ametrics\"\xa1\x01\n" +
	"\n" +
	"LogRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"image_uuid\x18\x02 \x01(\tR\timageUuid\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12+\n" +
	"\x11transformation_id\x18\x05 \x01(\x05R\x10transformationId\"\x1d\n" +
	"\vLogResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"'\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xb7\x04\n" +
	"\fOrchestrator\x12I\n" +
	"\fRegisterNode\x12\x1b.worker.RegisterNodeRequest\x1a\x1c.worker.RegisterNodeResponse\x123\n" +
	"\bLogEvent\x12\x12.worker.LogRequest\x1a\x13.worker.LogResponse\x126\n" +
	"\tPullTasks\x12\x13.worker.PullRequest\x1a\x14.worker.PullResponse\x12/\n" +
	"\fSubmitResult\x12\x12.worker.TaskResult\x1a\v.worker.Ack\x129\n" +
	"\n" +
	"StealTasks\x12\x14.worker.StealRequest\x1a\x15.worker.StealResponse\x127\n" +
	"\x12UpdateTaskProgress\x12\x14.worker.TaskProgress\x1a\v.worker.Ack\x126\n" +
	"\rSendHeartbeat\x12\x18.worker.HeartbeatRequest\x1a\v.worker.Ack\x12I\n" +
	"\x0eGetQueueStatus\x12\x1a.worker.QueueStatusRequest\x1a\x1b.worker.QueueStatusResponse\x12G\n" +
	"\n" +
	"WatchQueue\x12\x1a.worker.QueueStatusRequest\x1a\x1b.worker.QueueStatusResponse0\x012\x86\x01\n" +
	"\n" +
	"WorkerNode\x12=\n" +
	"\n" +
	"GetMetrics\x12\x1a.worker.QueueStatusRequest\x1a\x13.worker.NodeMetrics\x129\n" +
	"\n" +
	"YieldTasks\x12\x14.worker.StealRequest\x1a\x15.worker.StealResponseB/\n" +
	"\x12enfok.worker.protoP\x01Z\x17orchestrator-node/protob\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_orchestrator_proto_goTypes = []any{
	(*TransformationItem)(nil),     // 0: worker.TransformationItem
	(*TransformationPipeline)(nil), // 1: worker.TransformationPipeline
	(*ImageTask)(nil),              // 2: worker.ImageTask
	(*NodeMetrics)(nil),            // 3: worker.NodeMetrics
	(*PullRequest)(nil),            // 4: worker.PullRequest
	(*PullResponse)(nil),           // 5: worker.PullResponse
	(*TaskResult)(nil),             // 6: worker.TaskResult
	(*StealRequest)(nil),           // 7: worker.StealRequest
	(*StealResponse)(nil),          // 8: worker.StealResponse
	(*TaskProgress)(nil),           // 9: worker.TaskProgress
	(*QueueStatusRequest)(nil),     // 10: worker.QueueStatusRequest
	(*NodeQueueInfo)(nil),          // 11: worker.NodeQueueInfo
	(*QueueStatusResponse)(nil),    // 12: worker.QueueStatusResponse
	(*RegisterNodeRequest)(nil),    // 13: worker.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),   // 14: worker.RegisterNodeResponse
	(*HeartbeatRequest)(nil),       // 15: worker.HeartbeatRequest
	(*LogRequest)(nil),             // 16: worker.LogRequest
	(*LogResponse)(nil),            // 17: worker.LogResponse
	(*Ack)(nil),                    // 18: worker.Ack
	nil,                            // 19: worker.ImageTask.MetadataEntry
	nil,                            // 20: worker.TaskResult.MetadataEntry
}
var file_orchestrator_proto_depIdxs = []int32{
	0,  // 0: worker.TransformationPipeline.items:type_name -> worker.TransformationItem
	1,  // 1: worker.ImageTask.transformation_pipeline:type_name -> worker.TransformationPipeline
	19, // 2: worker.ImageTask.metadata:type_name -> worker.ImageTask.MetadataEntry
	3,  // 3: worker.PullRequest.metrics:type_name -> worker.NodeMetrics
	2,  // 4: worker.PullResponse.tasks:type_name -> worker.ImageTask
	3,  // 5: worker.TaskResult.metrics:type_name -> worker.NodeMetrics
	20, // 6: worker.TaskResult.metadata:type_name -> worker.TaskResult.MetadataEntry
	2,  // 7: worker.StealResponse.stolen_tasks:type_name -> worker.ImageTask
	11, // 8: worker.QueueStatusResponse.nodes:type_name -> worker.NodeQueueInfo
	3,  // 9: worker.RegisterNodeRequest.metrics:type_name -> worker.NodeMetrics
	3,  // 10: worker.HeartbeatRequest.metrics:type_name -> worker.NodeMetrics
	13, // 11: worker.Orchestrator.RegisterNode:input_type -> worker.RegisterNodeRequest
	16, // 12: worker.Orchestrator.LogEvent:input_type -> worker.LogRequest
	4,  // 13: worker.Orchestrator.PullTasks:input_type -> worker.PullRequest
	6,  // 14: worker.Orchestrator.SubmitResult:input_type -> worker.TaskResult
	7,  // 15: worker.Orchestrator.StealTasks:input_type -> worker.StealRequest
	9,  // 16: worker.Orchestrator.UpdateTaskProgress:input_type -> worker.TaskProgress
	15, // 17: worker.Orchestrator.SendHeartbeat:input_type -> worker.HeartbeatRequest
	10, // 18: worker.Orchestrator.GetQueueStatus:input_type -> worker.QueueStatusRequest
	10, // 19: worker.Orchestrator.WatchQueue:input_type -> worker.QueueStatusRequest
	10, // 20: worker.WorkerNode.GetMetrics:input_type -> worker.QueueStatusRequest
	7,  // 21: worker.WorkerNode.YieldTasks:input_type -> worker.StealRequest
	14, // 22: worker.Orchestrator.RegisterNode:output_type -> worker.RegisterNodeResponse
	17, // 23: worker.Orchestrator.LogEvent:output_type -> worker.LogResponse
	5,  // 24: worker.Orchestrator.PullTasks:output_type -> worker.PullResponse
	18, // 25: worker.Orchestrator.SubmitResult:output_type -> worker.Ack
	8,  // 26: worker.Orchestrator.StealTasks:output_type -> worker.StealResponse
	18, // 27: worker.Orchestrator.UpdateTaskProgress:output_type -> worker.Ack
	18, // 28: worker.Orchestrator.SendHeartbeat:output_type -> worker.Ack
	12, // 29: worker.Orchestrator.GetQueueStatus:output_type -> worker.QueueStatusResponse
	12, // 30: worker.Orchestrator.WatchQueue:output_type -> worker.QueueStatusResponse
	3,  // 31: worker.WorkerNode.GetMetrics:output_type -> worker.NodeMetrics
	8,  // 32: worker.WorkerNode.YieldTasks:output_type -> worker.StealResponse
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
